# Generated by Django 4.2.7 on 2023-12-01 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_alter_task_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
