# Generated by Django 4.2.7 on 2023-12-03 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserInterface', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
